### ISSUE TITLE
Feel free to fork my educational articles

### ISSUE THREAD

**Issue by kadenzipfel** [gakonst/solidity-book#1]
I wrote some articles a while back that might be super useful for this book. Feel free to use however you like.

Gas optimizations: https://betterprogramming.pub/how-to-write-smart-contracts-that-optimize-gas-spent-on-ethereum-30b5e9c5db85
Smart contract security: https://betterprogramming.pub/the-encyclopedia-of-smart-contract-attacks-vulnerabilities-dfc1129fdaac

**Comment by gakonst** [comment]
moved to https://github.com/gakonst/solidity-book/issues/8
