### ISSUE TITLE
EVM Articles

### ISSUE THREAD

**Issue by lucas-manuel** [gakonst/solidity-book#7]
Here are some good EVM-related articles that we could provide a modernized summary of:

- https://programtheblockchain.com/posts/2018/03/09/understanding-ethereum-smart-contract-storage/
- https://blog.qtum.org/diving-into-the-ethereum-vm-6e8d5d2f3c30
- https://medium.com/@hayeah/diving-into-the-ethereum-vm-part-2-storage-layout-bc5349cb11b7
- https://medium.com/@hayeah/diving-into-the-ethereum-vm-the-hidden-costs-of-arrays-28e119f04a9b
- https://medium.com/@hayeah/how-to-decipher-a-smart-contract-method-call-8ee980311603

**Comment by gakonst** [comment]
moved to https://github.com/gakonst/solidity-book/issues/8
